export {
  canonicalizeCandidateDossier,
  canonicalizeCapabilityRequest,
  canonicalizeFitAssessmentRequest,
  canonicalizeFitAssessmentResult,
  canonicalizeRepositoryFingerprint,
} from './canonicalize.ts';
export {
  createStableId,
  MAXIMUM_DOMAIN_ISSUES,
  MAXIMUM_DOMAIN_ISSUE_MESSAGE_LENGTH,
  MAXIMUM_DOMAIN_ISSUE_PATH_LENGTH,
  STABLE_ID_MAX_LENGTH,
} from './issues.ts';
export {
  CAPABILITY_TAXONOMY_CONCEPT_KINDS,
  CAPABILITY_TAXONOMY_LIMITS,
  canonicalizeCapabilityTaxonomy,
  lookupCapabilityTaxonomyTerm,
  validateCapabilityTaxonomy,
} from './capability-taxonomy.ts';
export type {
  CapabilityTaxonomy,
  CapabilityTaxonomyAmbiguity,
  CapabilityTaxonomyConcept,
  CapabilityTaxonomyConceptKind,
  CapabilityTaxonomyExclusion,
  CapabilityTaxonomyLookupResult,
  CapabilityTaxonomyRecordStatus,
  CapabilityTaxonomyResolvedAlias,
} from './capability-taxonomy.ts';
export {
  CAPABILITY_QUERY_CONSTRAINT_FACETS,
  CAPABILITY_QUERY_LIMITS,
  CAPABILITY_QUERY_MAX_UNRESOLVED_TERMS,
  CAPABILITY_QUERY_NORMALIZER_VERSION,
  canonicalizeCapabilityQueryInput,
  validateCandidateReferenceAuthority,
  validateCapabilityQueryInput,
} from './capability-query.ts';
export type {
  CandidateReferenceAuthority,
  CandidateReferenceAuthorityEntry,
  CapabilityQueryCandidateReference,
  CapabilityQueryCandidateReferenceKind,
  CapabilityQueryConstraintFacet,
  CapabilityQueryConstraintModality,
  CapabilityQueryDraftConstraint,
  CapabilityQueryInput,
  CapabilityQueryOutcome,
  CapabilityQueryRepositoryFingerprintReference,
  CapabilityQuerySuccessCondition,
  CapabilityQueryTerm,
} from './capability-query.ts';
export {
  canonicalizeCapabilityQueryLookupTermV1,
  normalizeCapabilityQuery,
  validateCapabilityQueryNormalizationResult,
} from './capability-query-normalization.ts';
export {
  DETERMINISTIC_CANDIDATE_PROFILE_AUTHORITY_VERSION,
  DETERMINISTIC_CANDIDATE_PROFILE_VERSION,
  DETERMINISTIC_PROFILE_BROAD_RETRIEVAL_FACETS,
  DETERMINISTIC_PROFILE_DENOMINATOR_VERSION,
  DETERMINISTIC_PROFILE_FIELD_IDS,
  DETERMINISTIC_PROFILE_LAUNCH_HARD_FILTER_FACETS,
  DETERMINISTIC_PROFILE_RULES_VERSION,
  canonicalizeDeterministicCandidateProfile,
  getDeterministicProfileFieldRegistry,
  isFieldValue,
  validateDeterministicCandidateProfile,
  validateDeterministicCandidateProfileAuthority,
  validateDeterministicProfileFieldRegistry,
} from './deterministic-candidate-profile.ts';
export {
  CANDIDATE_CONSTRAINT_EVALUATION_VERSION,
  evaluateCandidateConstraintProfileState,
  evaluateCandidateConstraints,
} from './candidate-constraint-evaluation.ts';
export type {
  CandidateConstraintEvaluation,
  CandidateConstraintEvaluationInput,
  CandidateConstraintEvaluationItem,
  CandidateConstraintMatch,
  CandidateConstraintNormalizationInput,
  CandidateConstraintState,
} from './candidate-constraint-evaluation.ts';
export type {
  DeterministicCandidateProfile,
  DeterministicCandidateProfileAuthority,
  DeterministicProfileBroadRetrievalFacet,
  DeterministicProfileConflictClaim,
  DeterministicProfileExtractionRuleId,
  DeterministicProfileFieldDefinition,
  DeterministicProfileFieldId,
  DeterministicProfileFieldRecord,
  DeterministicProfileFieldScope,
  DeterministicProfileFieldState,
  DeterministicProfileIntendedUse,
  DeterministicProfileLaunchHardFilterFacet,
  DeterministicProfileSourceReference,
  DeterministicProfileStateReasonCode,
  DeterministicProfileStateRuleId,
  DeterministicProfileValue,
  DeterministicProfileValueByFieldId,
  DeterministicProfileValueKind,
  DeterministicProfileVersionScope,
  ProfileAdvisorySeverity,
  ProfileCatalogFieldCode,
  ProfileDatastore,
  ProfileFramework,
  ProfileLanguageEcosystem,
  ProfileProcessRole,
} from './deterministic-candidate-profile.ts';
export type {
  CapabilityQueryCandidateCatalogBinding,
  CapabilityQueryClarification,
  CapabilityQueryConstraintResolutionBasis,
  CapabilityQueryNormalizationCore,
  CapabilityQueryNormalizationSemanticResult,
  CapabilityQueryNormalizationNotice,
  CapabilityQueryNormalizationStep,
  CapabilityQueryTermCanonicalizationResult,
  CapabilityQueryUnresolvedTerm,
  NormalizedCapabilityConcept,
  NormalizedCapabilityConstraint,
  PreservedCapabilityQueryDeclaration,
  ResolvedCapabilityQueryCandidateReference,
} from './capability-query-normalization.ts';
export { getCapabilityFamilies } from './model.ts';
export {
  validateFitAssessmentExchange,
  validateFitAssessmentResult,
} from './assessment-validation.ts';
export {
  validateCandidateDossier,
  validateCapabilityRequest,
  validateFitAssessmentRequest,
  validateRepositoryFingerprint,
} from './request-validation.ts';
export {
  SUPPORTED_REPOSITORY_FACT_VOCABULARY_VERSION,
  getRepositoryFactVocabularySnapshot,
  isSupportedRepositoryFactVocabularyVersion,
  repositoryFactSemanticAssertion,
  repositoryFactSemanticKey,
  serializeRepositoryFactVocabulary,
  validateRepositoryFactSemantics,
} from './repository-fact-vocabulary.ts';
export type {
  RepositoryFactSemanticFailureReason,
  RepositoryFactSemanticValidationResult,
  RepositoryFactVocabularyDefinition,
  RepositoryFactVocabularySerializationResult,
  RepositoryFactVocabularySnapshot,
  RepositoryFactVocabularySnapshotResult,
  RepositoryFactPresenceState,
  SupportedRepositoryFactCode,
  SupportedRepositoryFactVocabularyVersion,
} from './repository-fact-vocabulary.ts';

export type {
  ApprovalId,
  AssessmentId,
  AssessmentProcessingReasonCode,
  AssessmentMaterialUnknown,
  AssessmentRequestId,
  CandidateAssessment,
  CandidateDisposition,
  CandidateDossier,
  CandidateId,
  CandidateIdentity,
  CandidateLimitation,
  CandidateMaterialUnknown,
  CandidateReason,
  CapabilityFamily,
  CapabilityRequest,
  CodedRepositoryFact,
  CodedRepositoryFactValue,
  DeploymentRepositoryFact,
  EvidenceDimension,
  EvidenceFreshness,
  EvidenceId,
  EvidenceObservation,
  EvidenceProvenance,
  EvidenceReference,
  ExplicitRankRelation,
  FingerprintId,
  FitAssessmentExchange,
  FitAssessmentRequest,
  FitAssessmentResult,
  HardConstraint,
  HardConstraintConflict,
  HardConstraintConflictId,
  HardConstraintId,
  IncomparablePair,
  Inference,
  InferenceId,
  LimitationId,
  LimitationCode,
  MaterialClaim,
  MaterialClaimId,
  MaterialUnknown,
  MaterialUnknownId,
  NamedVersionFactCategory,
  NamedVersionRepositoryFact,
  Preference,
  PreferenceId,
  RankGroup,
  ReasonCode,
  RepositoryFact,
  RepositoryFactCategory,
  RepositoryFactCode,
  RepositoryFactId,
  RepositoryFactProvenance,
  RepositoryFactSource,
  RepositoryFactSubjectCode,
  RepositoryFactValueCode,
  RepositoryFactVocabularyVersion,
  RepositoryFingerprint,
  RequestId,
  ResponsibleOutcome,
  StableId,
  StableIdKind,
  SuccessCondition,
  SuccessConditionId,
  TopicId,
  TransmissionApproval,
  TransmissionFactCategory,
  WithheldRepositoryCategory,
  ValidationReferenceId,
} from './model.ts';
export type { DomainIssue, DomainIssueCode, DomainResult } from './issues.ts';
